import { NextResponse } from "next/server";
import { writeFile, mkdir } from "fs/promises";
import { join } from "path";
import { existsSync } from "fs";

/**
 * POST /api/reports/upload
 * Upload report file generated by bot (internal API, bypass auth with X-Internal-Request header)
 */
export async function POST(request: Request) {
  try {
    // Check for internal request header (from bot)
    const isInternalRequest = request.headers.get("X-Internal-Request") === "true";
    
    // If not internal request, you could add additional validation here
    if (!isInternalRequest) {
      // Optional: add API key validation for external callers
      // const apiKey = request.headers.get("X-API-Key");
      // if (apiKey !== process.env.INTERNAL_API_KEY) {
      //   return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
      // }
    }

    const data = await request.formData();
    const file: File | null = data.get("file") as unknown as File;
    const reportType = data.get("reportType") as string | null;
    
    if (!file) {
      return NextResponse.json({ error: "No file provided" }, { status: 400 });
    }

    const bytes = await file.arrayBuffer();
    const buffer = Buffer.from(bytes);

    // Save to public/uploads/reports/
    const uploadDir = join(process.cwd(), "public", "uploads", "reports");
    if (!existsSync(uploadDir)) {
      await mkdir(uploadDir, { recursive: true });
    }

    const fileName = `${Date.now()}-${file.name.replace(/[^a-zA-Z0-9.-]/g, "")}`;
    const filePath = join(uploadDir, fileName);
    await writeFile(filePath, buffer);

    const url = `/uploads/reports/${fileName}`;
    return NextResponse.json({ url, filePath });
  } catch (error) {
    console.error("Upload error:", error);
    return NextResponse.json({ error: "Error uploading file" }, { status: 500 });
  }
}